name: Publish Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - id: modpack_file
      run: echo "path=$packPath" >> "$GITHUB_OUTPUT"
      env:
        packPath: "QT-Gang-SteamPunk-${{ github.ref_name }}.zip"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: workflow/nix-shell-action@v3.3.0
      with:
        packages: packwiz
        script: |
          packwiz curseforge export -o ${{ steps.modpack_file.outputs.path }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.modpack_file.outputs.path }}

